# Generated by Django 4.1.5 on 2023-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('withdraw', models.IntegerField()),
                ('deposit', models.IntegerField()),
            ],
        ),
    ]
